apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pytorch-vision-starter
  title: PyTorch Vision Starter
  description: A very cool template that creates a complete Python workspace for image classification using ResNet-18 and CUDA.
  tags:
    - python
    - ai
    - cuda
    - pytorch
    - vision
spec:
  owner: user:guest
  type: service

  # 1. PARAMETERS: This builds the UI form the user will see.
  parameters:
    - title: Project Information
      required:
        - project_name
        - img_num
      properties:
        project_name:
          title: Project Name
          type: string
          description: The name of your project (use hyphens instead of spaces, e.g., best-ever).
          ui:autofocus: true
        img_num:
          title: Image number
          type: integer
          description: The number of images that are given to the model.

  # 2. STEPS: The actions the hub performs after the form is submitted.
  steps:
    - id: fetch-skeleton
      name: Generate the code
      action: fetch:template
      input:
        url: https://bitbucket.org/learning_devops_co/pytorch-vision-skeleton/src/main/
        values:
          project_name: ${{ parameters.project_name }}
          img_num: ${{ parameters.img_num }}

    - id: publish
      name: publish the new repository
      action: publish:bitbucketCloud
      input:
        # Added the required project key to the URL string
        repoUrl: 'bitbucket.org?workspace=learning_devops_co&project=PYT&repo=${{ parameters.project_name }}'
        description: "Generated PyTorch Vision Model"

    - id: register
      name: register in developer hub
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
    
  output:
    links:
      - title: Go to your new Bitbucket Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Developer Hub Catalog
        url: ${{ steps.register.output.catalogInfoUrl }}
