apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pytorch-vision-starter
  title: PyTorch Vision Starter
  description: A very cool template that creates a complete Python workspace for image classification using ResNet-18 and CUDA.
  tags:
    - python
    - ai
    - cuda
    - pytorch
    - vision
spec:
  owner: user:guest
  type: service

  # 1. PARAMETERS: This builds the UI form the user will see.
  parameters:
    - title: Project Information
      required:
        - project_name
        - img_num
        - pip_or_conda
      properties:
        project_name:
          title: Project Name
          type: string
          description: The name of your project.
          ui:autofocus: true
        img_num:
          title: Image number
          type: integer
          description: The number of images that are given to the model.
        pip_or_conda:
          title: pip or conda
          type: string
          enum: 
            - pip
            - conda
          description: Choose your preferred package manager.

  # 2. STEPS: The actions the hub performs after the form is submitted.
  steps:
    - id: log-step
      name: Log Model Creation
      action: debug:log
      input:
        message: "Starting setup for the ${{ parameters.project_name }} Project, with ${{ parameters.img_num }} images, using ${{ paramteres.pip_or_conda }}!"
